# Workflow name
name: Build and test with gradle

on:
  # When it will be triggered
  # And in which branch
  pull_request:
  push:
    branches:
      - main
      - develop

# Where will they run
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      ## Checkout our repository ###
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build app
        uses: eskatos/gradle-command-action@v1.3.3
        run: ./gradlew build -x test
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Run unit tests
        uses: eskatos/gradle-command-action@v1.3.3
        run: ./gradlew test
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Archive JUnit Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: gradle-report-jdk-11
          path: '**/build/reports/tests/'