# Workflow name
name: Build and test with gradle

on:
  # When it will be triggered
  # And in which branch
  pull_request:
  push:
    branches:
      - main
      - develop

# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## Checkout our repository ###
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

  test:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute app test
        run: ./gradlew test

      - name: Archive JUnit Report
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: gradle-report-jdk-11
          path: '**/build/reports/tests/'